# Generated by Django 4.1.4 on 2022-12-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('tconst', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('titleType', models.CharField(max_length=150)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageReting', models.CharField(max_length=10)),
                ('numVotes', models.IntegerField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movies')),
            ],
        ),
    ]
